#!/bin/bash
set -eo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ADDRESSES_FILE="$SCRIPT_DIR/frontend/constants/addresses.ts"

extract_address() {
  local label="$1"
  local log_file="$2"
  local line
  local address

  line=$(grep -F "${label}:" "$log_file" | tail -n1 || true)
  address=$(printf '%s\n' "$line" | grep -oE '0x[0-9a-fA-F]{40}' | head -n1 || true)

  if [ -z "$address" ]; then
    echo "❌ Could not extract ${label} address from deployment output."
    exit 1
  fi

  printf '%s' "$address"
}

write_frontend_addresses() {
  local weth="$1"
  local oracle="$2"
  local factory="$3"
  local router="$4"
  local gbp_stable="$5"
  local gbp_pool="$6"
  local usd_stable="$7"
  local usd_pool="$8"

  cat > "$ADDRESSES_FILE" <<EOF
// Auto-generated by deploy.sh. Do not edit manually.
export const CONTRACT_ADDRESSES = {
  WETH: "$weth",
  ORACLE: "$oracle",
  FACTORY: "$factory",
  ROUTER: "$router",
  GBP_STABLE: "$gbp_stable",
  GBP_POOL: "$gbp_pool",
  USD_Stable: "$usd_stable",
  USD_Pool: "$usd_pool"
} as const;
EOF
}

echo "🚀 Starting deployment..."

# -------------------------------
# Run everything in a subshell to isolate environment
# -------------------------------
(
  cd "$SCRIPT_DIR"

  # -------------------------------
  # 1. Load environment variables temporarily
  # -------------------------------
  if [ -f "$SCRIPT_DIR/.env" ]; then
      echo "📄 Loading .env..."
      set -a  # auto-export all variables
      source "$SCRIPT_DIR/.env"
      set +a
  else
      echo "❌ .env file not found!"
      exit 1
  fi

  # -------------------------------
  # 2. Check required vars
  # -------------------------------
  if [ -z "$RPC_URL" ] || [ -z "$PRIVATE_KEY" ]; then
      echo "❌ RPC_URL or PRIVATE_KEY missing in .env"
      exit 1
  fi

  # -------------------------------
  # 3. Install dependencies
  # -------------------------------
  echo "📦 Installing dependencies..."
  forge install

  # -------------------------------
  # 4. Clean old builds (optional)
  # -------------------------------
  echo "🧹 Cleaning old build..."
  rm -rf out cache broadcast

  # -------------------------------
  # 5. Compile contracts
  # -------------------------------
  echo "🔨 Compiling..."
  forge build

  # -------------------------------
  # 6. Deploy contracts
  # -------------------------------
  echo "📡 Deploying contracts..."
  deploy_log_file="$(mktemp)"
  trap 'rm -f "$deploy_log_file"' EXIT

  forge script script/multix.s.sol:MultixScript \
      --rpc-url "$RPC_URL" \
      --broadcast \
      --private-key "$PRIVATE_KEY" \
      -vv | tee "$deploy_log_file"

  weth="$(extract_address "WETH" "$deploy_log_file")"
  oracle="$(extract_address "Oracle" "$deploy_log_file")"
  factory="$(extract_address "Factory" "$deploy_log_file")"
  router="$(extract_address "Router" "$deploy_log_file")"
  gbp_stable="$(extract_address "GBP Stable" "$deploy_log_file")"
  gbp_pool="$(extract_address "GBP Pool" "$deploy_log_file")"
  usd_stable="$(extract_address "USD Stable" "$deploy_log_file")"
  usd_pool="$(extract_address "USD Pool" "$deploy_log_file")"

  write_frontend_addresses \
    "$weth" \
    "$oracle" \
    "$factory" \
    "$router" \
    "$gbp_stable" \
    "$gbp_pool" \
    "$usd_stable" \
    "$usd_pool"

  echo "📝 Updated frontend addresses at $ADDRESSES_FILE"

  echo "✅ Deployment completed!"
)

# -------------------------------
# 7. End of subshell — environment variables destroyed automatically
# -------------------------------
echo "🔒 All sensitive environment variables have been removed from this shell session."