// Auto-generated by deploy.sh. Do not edit manually.
// EUR_STABLE/EUR_POOL/PKR_STABLE/PKR_POOL are manual additions (factory.createMarket
// called directly via cast, not through deploy.sh/multix.s.sol) - a future full
// deploy.sh run will overwrite this file and drop them; re-add after re-running
// createMarket for each currency if that happens.
export const CONTRACT_ADDRESSES = {
  WETH: "0x2cc688199982A4B489832344df17860A7033BaEa",
  ORACLE: "0x0E118934456f0CA503a409C98b2e13B00747DF6a",
  FACTORY: "0xe26535AbbC2012eBF9e73c4babE0aF1E074769bf",
  ROUTER: "0x7A8A5221E7855FE315E494b84A9aEF8686fb4513",
  GBP_STABLE: "0xD1233bEa81A447aF6DBC5FB6B74EeD92F9397945",
  GBP_POOL: "0xDad2fDd5fCc373f28Bf68665d41C2875C5e019fF",
  USD_Stable: "0x74Ac78F74e5cb03975Ef9D7b5A15A3F74Ab9AAa1",
  USD_Pool: "0xa6B1226beDaFE8c3912F8d0a5c3e467700999266",
  EUR_STABLE: "0x57EE5f7a7d04F7767e4aD0a72625daCA03E78B03",
  EUR_POOL: "0x3104AF8e0671194210810E54854dd15Af200fCC4",
  PKR_STABLE: "0x0f2643F0bc1A16e33b26eD76C7D38aC9A6c1F6eE",
  PKR_POOL: "0x748b4770494Eb691CF19781CcC064515887e0bF1"
} as const;
